# Generated by Django 4.1.7 on 2023-03-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_category_post_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                null=True, related_name="posts", to="blog.tag"
            ),
        ),
    ]
