# Generated by Django 4.1.7 on 2023-03-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="month_year",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
